name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: "Publish release"
    if: false
    runs-on: "ubuntu-latest"
    timeout-minutes: 30

    environment:
      name: deploy

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: 3.7
      - name: "Install dependencies"
        run: "scripts/install"
      - name: "Build package & docs"
        run: "scripts/build"
      - name: "Publish to PyPI & deploy docs"
        run: "scripts/publish"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
