---
name: Test Suite

on:
  workflow_dispatch:
    inputs:
      test-filter:
        description: "Optional pytest arguments to narrow the test run (e.g. -k name)"
        required: false
        default: ""

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-22.04"
    timeout-minutes: 30
    env:
      PIP_INDEX_URL: "https://:2023-05-16T10:59:53.927486Z@time-machines-pypi.sealsecurity.io/"

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: "scripts/install"
      - name: "Build package & docs"
        run: "scripts/build"
      - name: "Run tests"
        run: "scripts/test -v ${{ inputs.test-filter }}"
      - name: "Upload artifacts"
        if: matrix.python-version == '3.7'
        uses: actions/upload-artifact@v4
        with:
          name: starlette-dist
          path: "dist/*"
          if-no-files-found: error
